### ISSUE TITLE
Missing file of tnc_for_hyper_param_optimization.py?

### ISSUE THREAD

**Issue by scilearner** [Addison-Weatherhead/TRACE#2]
Hi, 

It's excellent work. Thanks for the open-source code.

In Readme file, it's said to run  `python -u -m tnc_for_hyper_param_optimization`, while tnc_for_hyper_param_optimization didn't exist and I found in .gitignore  there's tnc_for_hyper_param_optimization.py.

So, can you upload this file or check the command for training?

Thank you!

**Comment by Addison-Weatherhead** [comment]
Thanks for brining this up, I just pushed the file
